### ISSUE TITLE
Unable to retrieve long messages.

### ISSUE THREAD

**Issue by Radenfar** [terry3041/pyChatGPT#99] opened 2023-01-07 07:45 UTC
I'm trying to get a script for a video using the API.
ChatGPT pauses typing and after a long wait, the program crashes out with the following:
`Traceback (most recent call last):
  File "/Users/adamcomer/Documents/Python/youtube/app.py", line 60, in <module>
    main()
  File "/Users/adamcomer/Documents/Python/youtube/app.py", line 44, in main
    cc: content_creator = content_creator(title=title, api=api)
  File "/Users/adamcomer/Documents/Python/youtube/models/content_creator.py", line 40, in __init__
    self.content: str = get_content(self.title, api=self.api)
  File "/Users/adamcomer/Documents/Python/youtube/models/content_creator.py", line 21, in get_content
    content: str = str(api.send_message(message)['message'])[1:-1]
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pyChatGPT/pyChatGPT.py", line 431, in send_message
    WebDriverWait(self.driver, 120).until_not(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/selenium/webdriver/support/wait.py", line 110, in until_not
    value = method(self._driver)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/selenium/webdriver/support/expected_conditions.py", line 64, in _predicate
    return driver.find_element(*locator)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 861, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 444, in execute
    self.error_handler.check_response(response)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 249, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 300.000
  (Session info: chrome=108.0.5359.124)
Stacktrace:
0   35813dae657df94f_chromedriver       0x000000010d479f38 35813dae657df94f_chromedriver + 4910904
1   35813dae657df94f_chromedriver       0x000000010d3f9a03 35813dae657df94f_chromedriver + 4385283
2   35813dae657df94f_chromedriver       0x000000010d03e747 35813dae657df94f_chromedriver + 472903
3   35813dae657df94f_chromedriver       0x000000010d027427 35813dae657df94f_chromedriver + 377895
4   35813dae657df94f_chromedriver       0x000000010d0270a0 35813dae657df94f_chromedriver + 376992
5   35813dae657df94f_chromedriver       0x000000010d0257f2 35813dae657df94f_chromedriver + 370674
6   35813dae657df94f_chromedriver       0x000000010d025d18 35813dae657df94f_chromedriver + 371992
7   35813dae657df94f_chromedriver       0x000000010d03444c 35813dae657df94f_chromedriver + 431180
8   35813dae657df94f_chromedriver       0x000000010d035752 35813dae657df94f_chromedriver + 436050
9   35813dae657df94f_chromedriver       0x000000010d047db9 35813dae657df94f_chromedriver + 511417
10  35813dae657df94f_chromedriver       0x000000010d04d6cb 35813dae657df94f_chromedriver + 534219
11  35813dae657df94f_chromedriver       0x000000010d026224 35813dae657df94f_chromedriver + 373284
12  35813dae657df94f_chromedriver       0x000000010d047be0 35813dae657df94f_chromedriver + 510944
13  35813dae657df94f_chromedriver       0x000000010d0c41cb 35813dae657df94f_chromedriver + 1020363
14  35813dae657df94f_chromedriver       0x000000010d0a8ee3 35813dae657df94f_chromedriver + 909027
15  35813dae657df94f_chromedriver       0x000000010d07330c 35813dae657df94f_chromedriver + 688908
16  35813dae657df94f_chromedriver       0x000000010d07488e 35813dae657df94f_chromedriver + 694414
17  35813dae657df94f_chromedriver       0x000000010d4471de 35813dae657df94f_chromedriver + 4702686
18  35813dae657df94f_chromedriver       0x000000010d44bb19 35813dae657df94f_chromedriver + 4721433
19  35813dae657df94f_chromedriver       0x000000010d45328e 35813dae657df94f_chromedriver + 4752014
20  35813dae657df94f_chromedriver       0x000000010d44c91a 35813dae657df94f_chromedriver + 4725018
21  35813dae657df94f_chromedriver       0x000000010d420b02 35813dae657df94f_chromedriver + 4545282
22  35813dae657df94f_chromedriver       0x000000010d46b888 35813dae657df94f_chromedriver + 4851848
23  35813dae657df94f_chromedriver       0x000000010d46ba05 35813dae657df94f_chromedriver + 4852229
24  35813dae657df94f_chromedriver       0x000000010d481e5f 35813dae657df94f_chromedriver + 4943455
25  libsystem_pthread.dylib             0x00007fff2031c8fc _pthread_start + 224
26  libsystem_pthread.dylib             0x00007fff20318443 thread_start + 15`

Python version: 3.9
Running on Macbook M1, Big Sur 11.5.2
Simple message request causing error.

**Comment by terry3041** [comment] 2023-01-10 07:02
Duplicate of #62.

**Closed by terry3041** 2023-01-10 07:02 UTC
