### ISSUE TITLE
Response (send_message) not giving back results and throwing error

### ISSUE THREAD

**Issue by Anjaneya-Turai** [terry3041/pyChatGPT#53] opened 2022-12-21 09:23 UTC
```
def chatgpt_api_request(api, movie):
    response = api.send_message("Give me a 200 word movie plot line description of the Bollywood movie " + movie + " without character names in it and do not start with the movie title")
    print(response)
    return response["message"]
for idx in plots_list_df.index:
    movie = plots_list_df.iloc[idx, 0]
    response = chatgpt_api_request(api, movie)
    print(response)
    plots_list_df.iloc[idx, 1] = response
    
plots_list_df
```

**The response is not getting back...**

**ERROR -** 
IndexError                                Traceback (most recent call last)
<ipython-input-52-6ee085202f18> in <module>
      1 for idx in plots_list_df.index:
      2     movie = plots_list_df.iloc[idx, 0]
----> 3     response = chatgpt_api_request(api, movie)
      4     print(response)
      5     plots_list_df.iloc[idx, 1] = response

<ipython-input-51-923579c1ba02> in chatgpt_api_request(api, movie)
      1 def chatgpt_api_request(api, movie):
----> 2     response = api.send_message("Give me a 200 word movie plot line description of the Bollywood movie " + movie + " without character names in it and do not start with the movie title")
      3     print(response)
      4     return response["message"]

~\anaconda3\lib\site-packages\pyChatGPT\pyChatGPT.py in send_message(self, message)
    393         # Get the response element
    394         self.__verbose_print('[send_msg] Finding response element')
--> 395         response = self.driver.find_elements(
    396             By.XPATH, "//div[starts-with(@class, 'markdown prose break-words')]"
    397         )[-1]

IndexError: list index out of range
[ChatGPT Movie.zip](https://github.com/terry3041/pyChatGPT/files/10276399/ChatGPT.Movie.zip)

**Comment by DevRoss** [comment] 2022-12-21 12:41
These two PR have fixed it:
#52 
#42 

This is caused by the xpath looking for the reply

**Comment by terry3041** [comment] 2022-12-22 04:04
Should be fixed in v0.3.9.5.

**Closed by terry3041** 2022-12-22 04:04 UTC

**Comment by Anjaneya-Turai** [comment] 2022-12-22 06:22
> Should be fixed in v0.3.9.5.

When can we expect the newer version to be released?

**Comment by terry3041** [comment] 2022-12-22 06:24
> When can we expect the newer version to be released?

It is released. Update your library by `pip install -U pyChatGPT`.

**Comment by Anjaneya-Turai** [comment] 2022-12-22 06:27
> It is released. Update your library by `pip install -U pyChatGPT`.

This is not yet resolved in the newer version

**Comment by Anjaneya-Turai** [comment] 2022-12-22 06:27
Still getting the same error
